{
    'af': ('af', 'za'),            # Afrikaans (South Africa)
    'sq': ('sq', 'al'),            # Albanian (Albania)
    'ar': ('ar', 'sa'),            # Arabic (Saudi Arabia)
    'hy': ('hy', 'am'),            # Armenian (Armenia)
    'bn': ('bn', 'bd'),            # Bengali (Bangladesh)
    'bs': ('bs', 'ba'),            # Bosnian (Bosnia and Herzegovina)
    'ca': ('ca', 'es'),            # Catalan (Spain)
    'hr': ('hr', 'hr'),            # Croatian (Croatia)
    'cs': ('cs', 'cz'),            # Czech (Czech Republic)
    'da': ('da', 'dk'),            # Danish (Denmark)
    'nl': ('nl', 'nl'),            # Dutch (Netherlands)
    'en': ('en', 'us'),            # English (United States)
    'eo': ('eo', 'int'),           # Esperanto (International)
    'et': ('et', 'ee'),            # Estonian (Estonia)
    'tl': ('tl', 'ph'),            # Filipino (Philippines)
    'fi': ('fi', 'fi'),            # Finnish (Finland)
    'fr': ('fr', 'fr'),            # French (France)
    'de': ('de', 'de'),            # German (Germany)
    'el': ('el', 'gr'),            # Greek (Greece)
    'gu': ('gu', 'in'),            # Gujarati (India)
    'he': ('he', 'il'),            # Hebrew (Israel)
    'hi': ('hi', 'in'),            # Hindi (India)
    'hu': ('hu', 'hu'),            # Hungarian (Hungary)
    'is': ('is', 'is'),            # Icelandic (Iceland)
    'id': ('id', 'id'),            # Indonesian (Indonesia)
    'it': ('it', 'it'),            # Italian (Italy)
    'ja': ('ja', 'jp'),            # Japanese (Japan)
    'jw': ('jw', 'id'),            # Javanese (Indonesia)
    'kn': ('kn', 'in'),            # Kannada (India)
    'km': ('km', 'kh'),            # Khmer (Cambodia)
    'ko': ('ko', 'kr'),            # Korean (South Korea)
    'la': ('la', 'va'),            # Latin (Vatican City)
    'lv': ('lv', 'lv'),            # Latvian (Latvia)
    'lt': ('lt', 'lt'),            # Lithuanian (Lithuania)
    'lu': ('lu', 'lu'),            # Luxembourgish (Luxembourg)
    'mk': ('mk', 'mk'),            # Macedonian (North Macedonia)
    'ml': ('ml', 'in'),            # Malayalam (India)
    'mi': ('mi', 'nz'),            # Maori (New Zealand)
    'mr': ('mr', 'in'),            # Marathi (India)
    'my': ('my', 'mm'),            # Burmese (Myanmar)
    'ne': ('ne', 'np'),            # Nepali (Nepal)
    'no': ('no', 'no'),            # Norwegian (Norway)
    'pl': ('pl', 'pl'),            # Polish (Poland)
    'pt': ('pt', 'br'),            # Portuguese (Brazil)
    'pa': ('pa', 'in'),            # Punjabi (India)
    'ro': ('ro', 'ro'),            # Romanian (Romania)
    'ru': ('ru', 'ru'),            # Russian (Russia)
    'sr': ('sr', 'rs'),            # Serbian (Serbia)
    'si': ('si', 'lk'),            # Sinhala (Sri Lanka)
    'sk': ('sk', 'sk'),            # Slovak (Slovakia)
    'sl': ('sl', 'si'),            # Slovenian (Slovenia)
    'es': ('es', 'es'),            # Spanish (Spain)
    'su': ('su', 'id'),            # Sundanese (Indonesia)
    'sw': ('sw', 'tz'),            # Swahili (Tanzania)
    'sv': ('sv', 'se'),            # Swedish (Sweden)
    'tg': ('tg', 'tj'),            # Tajik (Tajikistan)
    'ta': ('ta', 'in'),            # Tamil (India)
    'te': ('te', 'in'),            # Telugu (India)
    'th': ('th', 'th'),            # Thai (Thailand)
    'tr': ('tr', 'tr'),            # Turkish (Turkey)
    'uk': ('uk', 'ua'),            # Ukrainian (Ukraine)
    'ur': ('ur', 'pk'),            # Urdu (Pakistan)
    'vi': ('vi', 'vn'),            # Vietnamese (Vietnam)
    'cy': ('cy', 'gb'),            # Welsh (United Kingdom)
    'xh': ('xh', 'za'),            # Xhosa (South Africa)
    'yi': ('yi', 'us'),            # Yiddish (United States)
    'zu': ('zu', 'za')             # Zulu (South Africa)
}
# With full accents and locale
{
    'af': ('af', 'za'),            # Afrikaans (South Africa)
    'sq': ('sq', 'al'),            # Albanian (Albania)
    'ar': ('ar', 'sa'),            # Arabic (Saudi Arabia)
    'ar-ae': ('ar', 'ae'),         # Arabic (UAE)
    'ar-bh': ('ar', 'bh'),         # Arabic (Bahrain)
    'ar-dz': ('ar', 'dz'),         # Arabic (Algeria)
    'ar-eg': ('ar', 'eg'),         # Arabic (Egypt)
    'ar-iq': ('ar', 'iq'),         # Arabic (Iraq)
    'ar-jo': ('ar', 'jo'),         # Arabic (Jordan)
    'ar-kw': ('ar', 'kw'),         # Arabic (Kuwait)
    'ar-lb': ('ar', 'lb'),         # Arabic (Lebanon)
    'ar-ly': ('ar', 'ly'),         # Arabic (Libya)
    'ar-ma': ('ar', 'ma'),         # Arabic (Morocco)
    'ar-om': ('ar', 'om'),         # Arabic (Oman)
    'ar-qa': ('ar', 'qa'),         # Arabic (Qatar)
    'ar-sa': ('ar', 'sa'),         # Arabic (Saudi Arabia)
    'ar-sy': ('ar', 'sy'),         # Arabic (Syria)
    'ar-ye': ('ar', 'ye'),         # Arabic (Yemen)
    'hy': ('hy', 'am'),            # Armenian (Armenia)
    'bn': ('bn', 'bd'),            # Bengali (Bangladesh)
    'bs': ('bs', 'ba'),            # Bosnian (Bosnia and Herzegovina)
    'ca': ('ca', 'es'),            # Catalan (Spain)
    'hr': ('hr', 'hr'),            # Croatian (Croatia)
    'cs': ('cs', 'cz'),            # Czech (Czech Republic)
    'da': ('da', 'dk'),            # Danish (Denmark)
    'nl': ('nl', 'nl'),            # Dutch (Netherlands)
    'en': ('en', 'us'),            # English (United States)
    'en-au': ('en', 'au'),         # English (Australia)
    'en-uk': ('en', 'uk'),         # English (United Kingdom)
    'en-ca': ('en', 'ca'),         # English (Canada)
    'en-in': ('en', 'in'),         # English (India)
    'en-nz': ('en', 'nz'),         # English (New Zealand)
    'en-sg': ('en', 'sg'),         # English (Singapore)
    'eo': ('eo', 'int'),           # Esperanto (International)
    'et': ('et', 'ee'),            # Estonian (Estonia)
    'tl': ('tl', 'ph'),            # Filipino (Philippines)
    'fi': ('fi', 'fi'),            # Finnish (Finland)
    'fr': ('fr', 'fr'),            # French (France)
    'fr-be': ('fr', 'be'),         # French (Belgium)
    'fr-ca': ('fr', 'ca'),         # French (Canada)
    'fr-ch': ('fr', 'ch'),         # French (Switzerland)
    'de': ('de', 'de'),            # German (Germany)
    'de-at': ('de', 'at'),         # German (Austria)
    'de-ch': ('de', 'ch'),         # German (Switzerland)
    'el': ('el', 'gr'),            # Greek (Greece)
    'gu': ('gu', 'in'),            # Gujarati (India)
    'he': ('he', 'il'),            # Hebrew (Israel)
    'hi': ('hi', 'in'),            # Hindi (India)
    'hu': ('hu', 'hu'),            # Hungarian (Hungary)
    'is': ('is', 'is'),            # Icelandic (Iceland)
    'id': ('id', 'id'),            # Indonesian (Indonesia)
    'it': ('it', 'it'),            # Italian (Italy)
    'ja': ('ja', 'jp'),            # Japanese (Japan)
    'jw': ('jw', 'id'),            # Javanese (Indonesia)
    'kn': ('kn', 'in'),            # Kannada (India)
    'km': ('km', 'kh'),            # Khmer (Cambodia)
    'ko': ('ko', 'kr'),            # Korean (South Korea)
    'la': ('la', 'va'),            # Latin (Vatican City)
    'lv': ('lv', 'lv'),            # Latvian (Latvia)
    'lt': ('lt', 'lt'),            # Lithuanian (Lithuania)
    'lu': ('lu', 'lu'),            # Luxembourgish (Luxembourg)
    'mk': ('mk', 'mk'),            # Macedonian (North Macedonia)
    'ml': ('ml', 'in'),            # Malayalam (India)
    'mi': ('mi', 'nz'),            # Maori (New Zealand)
    'mr': ('mr', 'in'),            # Marathi (India)
    'my': ('my', 'mm'),            # Burmese (Myanmar)
    'ne': ('ne', 'np'),            # Nepali (Nepal)
    'no': ('no', 'no'),            # Norwegian (Norway)
    'pl': ('pl', 'pl'),            # Polish (Poland)
    'pt': ('pt', 'br'),            # Portuguese (Brazil)
    'pt-pt': ('pt', 'pt'),          # Portuguese (Portugal)
    'pa': ('pa', 'in'),            # Punjabi (India)
    'ro': ('ro', 'ro'),            # Romanian (Romania)
    'ru': ('ru', 'ru'),            # Russian (Russia)
    'sr': ('sr', 'rs'),            # Serbian (Serbia)
    'si': ('si', 'lk'),            # Sinhala (Sri Lanka)
    'sk': ('sk', 'sk'),            # Slovak (Slovakia)
    'sl': ('sl', 'si'),            # Slovenian (Slovenia)
    'es': ('es', 'es'),            # Spanish (Spain)
    'es-mx': ('es', 'mx'),         # Spanish (Mexico)
    'es-ca': ('es', 'ca'),         # Spanish (Catalonia)
    'su': ('su', 'id'),            # Sundanese (Indonesia)
    'sw': ('sw', 'tz'),            # Swahili (Tanzania)
    'sv': ('sv', 'se'),            # Swedish (Sweden)
    'tg': ('tg', 'tj'),            # Tajik (Tajikistan)
    'ta': ('ta', 'in'),            # Tamil (India)
    'te': ('te', 'in'),            # Telugu (India)
    'th': ('th', 'th'),            # Thai (Thailand)
    'tr': ('tr', 'tr'),            # Turkish (Turkey)
    'uk': ('uk', 'ua'),            # Ukrainian (Ukraine)
    'ur': ('ur', 'pk'),            # Urdu (Pakistan)
    'vi': ('vi', 'vn'),            # Vietnamese (Vietnam)
    'cy': ('cy', 'gb'),            # Welsh (United Kingdom)
    'xh': ('xh', 'za'),            # Xhosa (South Africa)
    'yi': ('yi', 'us'),            # Yiddish (United States)
    'zu': ('zu', 'za')             # Zulu (South Africa)
}
